"""
embedded/export_weights.py

Exports a REAL NexusBrain PPO policy network's weights (same MLP class
used in brain/rl/ppo_agent.py, same dims used across the NEXUS demos:
state_dim=12 [6 base features + 2*3 obstacles, matching
environment/gym_wrapper.py's default n_obstacles=3], hidden_dim=64,
n_actions=5) into a C header the embedded port includes verbatim.

This is not hand-picked "nice" numbers - it's the actual Xavier/Glorot-
initialized weight matrices NEXUS's PPOAgent constructs, run through the
identical forward-pass math (x @ W1 + b1 -> tanh -> @ W2 + b2), so the C
port's output can be checked against the Python original bit-for-bit
(within the tanh-LUT approximation error - see tanh_lut.h).

Run: python3 embedded/export_weights.py > embedded/weights_state.h
"""
import sys
import numpy as np

sys.path.insert(0, ".")
from brain.rl.ppo_agent import MLP  # noqa: E402

STATE_DIM = 12   # 6 + 2*n_obstacles, n_obstacles=3 (environment/gym_wrapper.py default)
HIDDEN_DIM = 64  # brain/rl/ppo_agent.py PPOAgent default hidden_dim
N_ACTIONS = 5    # environment/gym_wrapper.py Discrete(5)

SEED = 42  # fixed seed so the exported header is reproducible


def c_array_1d(name: str, arr: np.ndarray) -> str:
    vals = ", ".join(f"{v:.8f}f" for v in arr)
    return f"static const float {name}[{arr.shape[0]}] = {{{vals}}};"


def c_array_2d(name: str, arr: np.ndarray) -> str:
    rows = []
    for row in arr:
        vals = ", ".join(f"{v:.8f}f" for v in row)
        rows.append(f"  {{{vals}}}")
    body = ",\n".join(rows)
    return f"static const float {name}[{arr.shape[0]}][{arr.shape[1]}] = {{\n{body}\n}};"


def main():
    rng = np.random.default_rng(SEED)
    policy = MLP(STATE_DIM, HIDDEN_DIM, N_ACTIONS, rng)

    # A fixed, plausible sensor/state reading to feed the embedded loop each
    # iteration - values in a realistic range for the ring-sensor + velocity
    # + relative-obstacle-position state vector NEXUS actually uses, not
    # zeros (zeros would let a buggy port hide behind a degenerate input).
    state = rng.uniform(-1.0, 1.0, size=STATE_DIM).astype(np.float64)

    # Also emit a matching "world facts" scenario for the safety veto rules,
    # deliberately chosen so exactly ONE veto rule (collision_imminent)
    # should fire - this is what the C port's output is checked against.
    battery_pct = 47.0
    min_obstacle_distance = 0.21   # < 0.3 -> collision_imminent_halt should fire
    in_bounds = 1
    steps_since_last_comm = 2
    comm_timeout_steps = 30

    print("/* AUTO-GENERATED by embedded/export_weights.py - do not hand-edit.\n"
          " * Real Xavier-initialized PPOAgent policy-network weights (seed=42),\n"
          " * dims matching brain/rl/ppo_agent.py + environment/gym_wrapper.py. */\n")
    print(f"#define NEXUS_STATE_DIM {STATE_DIM}")
    print(f"#define NEXUS_HIDDEN_DIM {HIDDEN_DIM}")
    print(f"#define NEXUS_N_ACTIONS {N_ACTIONS}\n")

    print(c_array_2d("W1", policy.W1))
    print(c_array_1d("B1", policy.b1))
    print(c_array_2d("W2", policy.W2))
    print(c_array_1d("B2", policy.b2))
    print(c_array_1d("INPUT_STATE", state))

    print(f"\n/* Safety-veto test scenario facts (mirrors safety/constitutional_ai.py) */")
    print(f"#define FACT_BATTERY_PCT {battery_pct}f")
    print(f"#define FACT_MIN_OBSTACLE_DISTANCE {min_obstacle_distance}f")
    print(f"#define FACT_IN_BOUNDS {in_bounds}")
    print(f"#define FACT_STEPS_SINCE_LAST_COMM {steps_since_last_comm}")
    print(f"#define FACT_COMM_TIMEOUT_STEPS {comm_timeout_steps}")
    print(f"#define HALT_ACTION 0")

    # Also print the Python-side ground-truth forward pass result to stderr
    # so it can be diffed against the QEMU-side printed output by hand.
    logits = policy.forward(state)
    action = int(np.argmax(logits))
    print(f"/* Python ground truth: policy logits = {list(np.round(logits, 6))}, "
          f"argmax action = {action} */", file=sys.stderr)
    print(f"/* Python ground truth: policy logits = {list(np.round(logits, 6))}, "
          f"argmax action (pre-safety-veto) = {action} */")


if __name__ == "__main__":
    main()
